name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'evoluservices'
        type: choice
        options:
          - 'evoluservices'
          - 'staging'
          - 'production'

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: staging
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      CONFLUENT_CLOUD_API_KEY: ${{ secrets.CONFLUENT_CLOUD_API_KEY }}
      CONFLUENT_CLOUD_API_SECRET: ${{ secrets.CONFLUENT_CLOUD_API_SECRET }}
      TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      TF_VAR_mysql_password: ${{ secrets.MYSQL_PASSWORD }}
      TF_VAR_connector_aws_access_key: ${{ secrets.CONNECTOR_AWS_ACCESS_KEY }}
      TF_VAR_connector_aws_secret_key: ${{ secrets.CONNECTOR_AWS_SECRET_KEY }}
      TF_VAR_connector_dynamodb_access_key: ${{ secrets.CONNECTOR_DYNAMODB_ACCESS_KEY }}
      TF_VAR_connector_dynamodb_secret_key: ${{ secrets.CONNECTOR_DYNAMODB_SECRET_KEY }}
      TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
      
      - name: Terraform Init
        run: |
          cd terraform/environments/${{ github.event.inputs.environment }}
          terraform init
      
      - name: Terraform Apply Destroy
        run: |
          cd terraform/environments/${{ github.event.inputs.environment }}
          terraform apply -destroy -auto-approve -var-file=terraform.tfvars